# Generated by Django 2.1.5 on 2020-06-01 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customerID',
            new_name='customer',
        ),
    ]
