# Generated by Django 2.1.5 on 2020-06-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200601_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toppings',
            name='pizza',
        ),
        migrations.AddField(
            model_name='pizzaorder',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='pizza', to='orders.Toppings'),
        ),
    ]
