# Generated by Django 2.1.5 on 2020-06-01 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200601_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotPizzaBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('size', models.CharField(blank=True, max_length=16)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='NotPizzaOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base', to='orders.NotPizzaBase')),
                ('sandwich_mod', models.ManyToManyField(blank=True, related_name='sub', to='orders.SubModifications')),
            ],
        ),
        migrations.RemoveField(
            model_name='notpizza',
            name='sandwich_mod',
        ),
        migrations.AlterField(
            model_name='order',
            name='not_pizza',
            field=models.ManyToManyField(blank=True, related_name='order', to='orders.NotPizzaOrder'),
        ),
        migrations.DeleteModel(
            name='NotPizza',
        ),
    ]
