# Generated by Django 2.1.5 on 2020-06-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200601_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notpizzabase',
            name='size',
            field=models.CharField(choices=[('SM', 'Small'), ('LG', 'Large'), ('NA', 'Not Applicable')], max_length=2),
        ),
    ]
